// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig AI配置结构（OpenAI 兼容格式）
 */
export class AIConfig {
    /**
     * Creates a new AIConfig instance.
     * @param {Partial<AIConfig>} [$$source = {}] - The source object to create the AIConfig.
     */
    constructor($$source = {}) {
        if (!("api_endpoint" in $$source)) {
            /**
             * API端点，如: https://api.openai.com/v1/chat/completions
             * @member
             * @type {string}
             */
            this["api_endpoint"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * API密钥
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * 模型名称，如: gpt-3.5-turbo, gpt-4
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * 超时时间（秒）
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("temperature" in $$source)) {
            /**
             * 温度参数 (0.0-2.0)，控制随机性
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("max_tokens" in $$source)) {
            /**
             * 最大生成 token 数
             * @member
             * @type {number}
             */
            this["max_tokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Top-p 采样参数 (0.0-1.0)
             * @member
             * @type {number | undefined}
             */
            this["top_p"] = undefined;
        }
        if (!("system_prompt" in $$source)) {
            /**
             * 系统提示词
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConfig(/** @type {Partial<AIConfig>} */($$parsedSource));
    }
}

/**
 * ChatMessage 前端显示用消息
 */
export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

/**
 * ChatRequest 前端发来的消息请求
 */
export class ChatRequest {
    /**
     * Creates a new ChatRequest instance.
     * @param {Partial<ChatRequest>} [$$source = {}] - The source object to create the ChatRequest.
     */
    constructor($$source = {}) {
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connId"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 深度思考（仅部分模型支持）
             * @member
             * @type {boolean | undefined}
             */
            this["deepThinking"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatRequest(/** @type {Partial<ChatRequest>} */($$parsedSource));
    }
}

/**
 * ChatResponse 返回给前端的响应
 */
export class ChatResponse {
    /**
     * Creates a new ChatResponse instance.
     * @param {Partial<ChatResponse>} [$$source = {}] - The source object to create the ChatResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatResponse(/** @type {Partial<ChatResponse>} */($$parsedSource));
    }
}
