// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService SSH服务结构体，供前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConnection 添加新连接（保存到本地）
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function AddConnection(conn) {
    return $Call.ByID(1087788240, conn);
}

/**
 * AddToGroup 将连接添加到分组
 * @param {string} groupID
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function AddToGroup(groupID, connID) {
    return $Call.ByID(3278328040, groupID, connID);
}

/**
 * AutoReconnect 自动重连（后台执行，不阻塞前端）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function AutoReconnect(connID) {
    return $Call.ByID(2337444059, connID);
}

/**
 * CancelDirectoryUpload 取消目录上传
 * @returns {$CancellablePromise<void>}
 */
export function CancelDirectoryUpload() {
    return $Call.ByID(4140435659);
}

/**
 * CancelSearch 取消正在进行的搜索
 * @param {string} connID
 * @param {string} searchID
 * @returns {$CancellablePromise<void>}
 */
export function CancelSearch(connID, searchID) {
    return $Call.ByID(1409975503, connID, searchID);
}

/**
 * CheckConnectionHealth 检查连接健康状态（心跳检测）
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckConnectionHealth(connID) {
    return $Call.ByID(2407550917, connID);
}

/**
 * ClearWindowPositions 清除所有窗口位置记忆
 * @returns {$CancellablePromise<void>}
 */
export function ClearWindowPositions() {
    return $Call.ByID(4159453682);
}

/**
 * CloseGroup 关闭分组（断开所有连接并删除分组）
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function CloseGroup(groupID) {
    return $Call.ByID(2899642454, groupID);
}

/**
 * CloseShellSession 关闭Shell会话（兼容旧调用，默认 session）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function CloseShellSession(connID) {
    return $Call.ByID(2079174541, connID);
}

/**
 * CloseShellSessionByID 关闭指定 session
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseShellSessionByID(connID, sessionID) {
    return $Call.ByID(3520039009, connID, sessionID);
}

/**
 * Connect 连接到SSH服务器
 * @param {string} connID
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function Connect(connID, config) {
    return $Call.ByID(1483559157, connID, config);
}

/**
 * CreateAndConnect 创建新连接并建立SSH连接（后端生成ID）
 * 流程：
 * 1. 生成唯一 connID
 * 2. 保存连接配置到本地存储
 * 3. 建立 SSH 连接
 * 4. 添加到默认分组
 * 5. 返回 connID 供前端打开窗口
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<string>}
 */
export function CreateAndConnect(config) {
    return $Call.ByID(945425304, config);
}

/**
 * CreateAndConnectWithGroup 创建连接并指定分组
 * @param {$models.SSHConfig | null} config
 * @param {string} groupID
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function CreateAndConnectWithGroup(config, groupID) {
    return $Call.ByID(21046451, config, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateArchive 创建压缩包并返回临时文件路径
 * @param {string} connID
 * @param {string[]} files
 * @param {string} archiveName
 * @returns {$CancellablePromise<string>}
 */
export function CreateArchive(connID, files, archiveName) {
    return $Call.ByID(3574852729, connID, files, archiveName);
}

/**
 * CreateDirectory 创建目录
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function CreateDirectory(connID, remotePath) {
    return $Call.ByID(3146491308, connID, remotePath);
}

/**
 * CreateGroup 创建新分组
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateGroup(name) {
    return $Call.ByID(1740096200, name);
}

/**
 * DeleteConnection 删除连接
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(4006810738, id);
}

/**
 * DeleteFile 删除文件
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(connID, remotePath) {
    return $Call.ByID(112508304, connID, remotePath);
}

/**
 * DeleteTempFile 删除临时文件
 * @param {string} connID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTempFile(connID, filePath) {
    return $Call.ByID(2125132178, connID, filePath);
}

/**
 * Disconnect 断开SSH连接（删除缓存记录，保留永久记录）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(connID) {
    return $Call.ByID(2529884119, connID);
}

/**
 * DownloadFile 下载文件（返回字节数组）
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFile(connID, remotePath) {
    return $Call.ByID(1900581067, connID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * ExecuteCommand 执行远程命令
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<$models.CommandResult | null>}
 */
export function ExecuteCommand(connID, command) {
    return $Call.ByID(4187821901, connID, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExtractArchive 解压压缩包到指定目录
 * @param {string} connID
 * @param {string} archivePath
 * @param {string} targetDir
 * @returns {$CancellablePromise<void>}
 */
export function ExtractArchive(connID, archivePath, targetDir) {
    return $Call.ByID(3963395040, connID, archivePath, targetDir);
}

/**
 * GetAllConnections 获取所有保存的连接（包含分组ID和真实在线状态）
 * @returns {$CancellablePromise<($models.ConnectionInfo | null)[]>}
 */
export function GetAllConnections() {
    return $Call.ByID(1008967299).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAllGroups 获取所有分组
 * @returns {$CancellablePromise<($models.SSHGroup | null)[]>}
 */
export function GetAllGroups() {
    return $Call.ByID(3250721886).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetApp 获取 Wails 应用实例（供其他服务使用）
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function GetApp() {
    return $Call.ByID(3921265510).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetClient 获取指定连接的 SSHClient（供其他服务使用）
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SSHClient | null>}
 */
export function GetClient(connID) {
    return $Call.ByID(3989033924, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetConnection 获取单个连接
 * @param {string} id
 * @returns {$CancellablePromise<$models.ConnectionInfo | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(1767912643, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetConnectionList 获取所有连接ID列表
 * @returns {$CancellablePromise<string[]>}
 */
export function GetConnectionList() {
    return $Call.ByID(605773803).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetDefaultGroupID 获取默认分组ID
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultGroupID() {
    return $Call.ByID(2852265946);
}

/**
 * GetExternalAgentAudit 扫描 root 与常见专用用户的授权密钥，并读取当前登录会话。
 * 扫描只读；返回值只包含算法、标签和指纹，不包含公钥正文。
 * @param {string} connID
 * @returns {$CancellablePromise<$models.ExternalAgentAudit | null>}
 */
export function GetExternalAgentAudit(connID) {
    return $Call.ByID(1988855236, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetExternalAgentScopeID 返回稳定的服务器级监管作用域 ID。
 * 同一服务器切换 root 和专用用户后仍使用同一份监管记录。
 * @param {string} connID
 * @returns {$CancellablePromise<string>}
 */
export function GetExternalAgentScopeID(connID) {
    return $Call.ByID(3622368146, connID);
}

/**
 * GetGroupByConnID 根据连接ID获取所属分组
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SSHGroup | null>}
 */
export function GetGroupByConnID(connID) {
    return $Call.ByID(567752624, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetGroupConnectionInfos 获取指定分组的完整连接信息
 * @param {string} groupID
 * @returns {$CancellablePromise<($models.ConnectionInfo | null)[]>}
 */
export function GetGroupConnectionInfos(groupID) {
    return $Call.ByID(1049785831, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetGroupConnections 获取指定分组的所有连接
 * @param {string} groupID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetGroupConnections(groupID) {
    return $Call.ByID(1893665799, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetLatency 获取连接延迟（实时测量）
 * @param {string} connID
 * @returns {$CancellablePromise<number>}
 */
export function GetLatency(connID) {
    return $Call.ByID(1796303915, connID);
}

/**
 * GetProcessDetail 获取进程详细信息
 * @param {string} connID
 * @param {number} pid
 * @returns {$CancellablePromise<string>}
 */
export function GetProcessDetail(connID, pid) {
    return $Call.ByID(1761678409, connID, pid);
}

/**
 * GetProcessList 获取进程列表
 * @param {string} connID
 * @returns {$CancellablePromise<$models.ProcessInfo[]>}
 */
export function GetProcessList(connID) {
    return $Call.ByID(2679255376, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetServerKey 根据连接 ID 返回服务器标识（host:port），供 AI 历史存储使用
 * @param {string} connID
 * @returns {$CancellablePromise<string>}
 */
export function GetServerKey(connID) {
    return $Call.ByID(2493801839, connID);
}

/**
 * GetSessionIDs 获取连接的所有活跃 session ID
 * @param {string} connID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSessionIDs(connID) {
    return $Call.ByID(3656916833, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSystemStats 获取系统资源统计
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SystemStats | null>}
 */
export function GetSystemStats(connID) {
    return $Call.ByID(453794585, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * IsConnected 检查连接状态
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected(connID) {
    return $Call.ByID(614771372, connID);
}

/**
 * IsDirectoryUploadCancelled 检查是否被取消
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDirectoryUploadCancelled() {
    return $Call.ByID(2946716868);
}

/**
 * IsShellActive 检查Shell会话是否活跃（兼容旧调用，默认 session）
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsShellActive(connID) {
    return $Call.ByID(4102491767, connID);
}

/**
 * IsShellSessionActive 检查指定 session 是否活跃
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsShellSessionActive(connID, sessionID) {
    return $Call.ByID(1797821969, connID, sessionID);
}

/**
 * KillProcess 终止进程
 * @param {string} connID
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function KillProcess(connID, pid) {
    return $Call.ByID(1867218666, connID, pid);
}

/**
 * ListDirectory 列出目录
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(connID, remotePath) {
    return $Call.ByID(2186396432, connID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ListFiles 列出目录内容
 * @param {string} connID
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListFiles(connID, path) {
    return $Call.ByID(4019260680, connID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * OpenSSHWindow 打开SSH分组窗口（如果已存在则聚焦，否则创建新窗口）
 * @param {string} groupID
 * @param {string} groupName
 * @param {string} activeConnID
 * @returns {$CancellablePromise<void>}
 */
export function OpenSSHWindow(groupID, groupName, activeConnID) {
    return $Call.ByID(2969027497, groupID, groupName, activeConnID);
}

/**
 * ReadFromShell 从Shell读取数据（兼容旧调用，默认 session）
 * @param {string} connID
 * @param {string} buf
 * @returns {$CancellablePromise<number>}
 */
export function ReadFromShell(connID, buf) {
    return $Call.ByID(1698637413, connID, buf);
}

/**
 * ReadFromShellSession 从指定 session 读取数据
 * @param {string} connID
 * @param {string} sessionID
 * @param {string} buf
 * @returns {$CancellablePromise<number>}
 */
export function ReadFromShellSession(connID, sessionID, buf) {
    return $Call.ByID(751379063, connID, sessionID, buf);
}

/**
 * Reconnect 重新连接（前端调用）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Reconnect(connID) {
    return $Call.ByID(1506103354, connID);
}

/**
 * RemoveFromGroup 从分组中移除连接
 * @param {string} groupID
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromGroup(groupID, connID) {
    return $Call.ByID(2990188000, groupID, connID);
}

/**
 * RenameFile 重命名文件/目录
 * @param {string} connID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(connID, oldPath, newPath) {
    return $Call.ByID(926601649, connID, oldPath, newPath);
}

/**
 * ResetDirectoryUploadCancel 重置取消标志
 * @returns {$CancellablePromise<void>}
 */
export function ResetDirectoryUploadCancel() {
    return $Call.ByID(1154651944);
}

/**
 * ResizeTerminal 调整终端大小（兼容旧调用）
 * @param {string} connID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(connID, cols, rows) {
    return $Call.ByID(1893537865, connID, cols, rows);
}

/**
 * ResizeTerminalByID 调整指定 session 的终端大小
 * @param {string} connID
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminalByID(connID, sessionID, cols, rows) {
    return $Call.ByID(534449829, connID, sessionID, cols, rows);
}

/**
 * RevokeExternalAgentKey 按指纹撤销指定账号的授权密钥。
 * root 可以管理所有账号；处理普通账号时会降权到目标账号执行文件操作，
 * 避免 root 直接写入低权限用户可控制的目录。
 * @param {string} connID
 * @param {string} username
 * @param {string} fingerprint
 * @returns {$CancellablePromise<void>}
 */
export function RevokeExternalAgentKey(connID, username, fingerprint) {
    return $Call.ByID(4230525060, connID, username, fingerprint);
}

/**
 * RunCommand 执行命令并返回输出字符串（供 AI 工具调用）
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RunCommand(connID, command) {
    return $Call.ByID(652415359, connID, command);
}

/**
 * SaveConnection 标记连接为已保存
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SaveConnection(id) {
    return $Call.ByID(1532054436, id);
}

/**
 * SearchFiles 递归搜索文件（支持子目录，流式返回）
 * @param {string} connID
 * @param {string} basePath
 * @param {string} keyword
 * @param {string} searchID
 * @returns {$CancellablePromise<void>}
 */
export function SearchFiles(connID, basePath, keyword, searchID) {
    return $Call.ByID(1665720024, connID, basePath, keyword, searchID);
}

/**
 * SelectLocalDirectoryAndUpload 选择本地目录并上传到远程服务器
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function SelectLocalDirectoryAndUpload(connID, remotePath) {
    return $Call.ByID(1587024721, connID, remotePath);
}

/**
 * SendSignal 向进程发送信号
 * @param {string} connID
 * @param {number} pid
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function SendSignal(connID, pid, signal) {
    return $Call.ByID(20195251, connID, pid, signal);
}

/**
 * SetApp 设置Wails应用实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3672340098, app);
}

/**
 * SetWindowManager 设置窗口管理器
 * @param {$models.WindowManager | null} wm
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowManager(wm) {
    return $Call.ByID(2749348190, wm);
}

/**
 * StartHealthCheck 启动健康检查定时器
 * @returns {$CancellablePromise<void>}
 */
export function StartHealthCheck() {
    return $Call.ByID(2883819847);
}

/**
 * StartShellSession 启动Shell会话（兼容旧调用，默认 sessionID = "default"）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function StartShellSession(connID) {
    return $Call.ByID(2475064529, connID);
}

/**
 * StartShellSessionWithID 启动指定 ID 的 Shell 会话
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StartShellSessionWithID(connID, sessionID) {
    return $Call.ByID(4239965024, connID, sessionID);
}

/**
 * SyncImportConnection 云端同步导入（按 host:port 去重：存在则更新，不存在则新增，永久保存）
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function SyncImportConnection(conn) {
    return $Call.ByID(1683906883, conn);
}

/**
 * TestConnection 测试SSH连接（连接成功后立即断开，不保存）
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(config) {
    return $Call.ByID(2198952405, config);
}

/**
 * UnsaveConnection 标记连接为未保存
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UnsaveConnection(id) {
    return $Call.ByID(3266349443, id);
}

/**
 * UpdateConnection 更新连接信息
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnection(conn) {
    return $Call.ByID(114569976, conn);
}

/**
 * UploadDirectory 上传目录
 * @param {string} connID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadDirectory(connID, localPath, remotePath) {
    return $Call.ByID(763209931, connID, localPath, remotePath);
}

/**
 * UploadFile 上传文件（从字节数组）
 * @param {string} connID
 * @param {string} remotePath
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(connID, remotePath, data) {
    return $Call.ByID(1901150526, connID, remotePath, data);
}

/**
 * WriteToTerminal 向终端写入数据（兼容旧调用）
 * @param {string} connID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToTerminal(connID, data) {
    return $Call.ByID(3974458965, connID, data);
}

/**
 * WriteToTerminalByID 向指定 session 写入数据
 * @param {string} connID
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToTerminalByID(connID, sessionID, data) {
    return $Call.ByID(112679593, connID, sessionID, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.CommandResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.ConnectionInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.SSHGroup.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = application$0.App.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.SSHClient.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $models.ExternalAgentAudit.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.ProcessInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.SystemStats.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.FileInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
